### PR TITLE
Add data-lk-orientation for kind video

### PR DESCRIPTION
**Pull request by nwang92**
This handles cases where `source === Track.Source.Unknown` but still has `kind === 'video'` using the same logic as https://github.com/livekit/components-js/blob/main/packages/react/src/components/participant/ParticipantTile.tsx#L155

### CODE REVIEW

**Review by Ocupe — APPROVED** [review]
I think that makes sense. Thank you for your contribution!

**Comment by lukasIO** [comment]
thanks for the PR! 
the difference to https://github.com/livekit/components-js/blob/main/packages/react/src/components/participant/ParticipantTile.tsx#L155 is that this referenced code is checking against `trackReference.source`. In the code here the check is against `publication.source`. 
I think your suggestion to check against `publication.kind` makes sense, but this makes the subsequent checks against `publication.source` redundant and we can remove them!

**Comment by nwang92** [comment]
> thanks for the PR! the difference to https://github.com/livekit/components-js/blob/main/packages/react/src/components/participant/ParticipantTile.tsx#L155 is that this referenced code is checking against `trackReference.source`. In the code here the check is against `publication.source`. I think your suggestion to check against `publication.kind` makes sense, but this makes the subsequent checks against `publication.source` redundant and we can remove them!

Done for useMediaTrackBySourceOrName.ts. Did you want to change this for ParticipantTile.tsx as well or should I leave it as-is?

**Review by lukasIO — APPROVED** [review]
looks good now, thanks!

**Pull request merged**
