### PR TITLE
Fix start audio component flash issue

### PR DESCRIPTION
**Pull request by harrisonlo**
Fix start audio component flash issue with canPlayAudio set to true by default until detected otherwise

### CODE REVIEW

**Review by Ocupe — APPROVED** [review]
@harrisonlo thanks for the PR. I think this is a reasonable change, especially because it fixes your problem. 👍
@lukasIO any objections?

**Comment by davidzhao** [comment]
I think this aligns with the client-sdk-js defaults as well: https://github.com/livekit/client-sdk-js#audio-playback

```
LiveKit takes an optimistic approach so it's possible for this value to change from true to false when we encounter a browser error.
```

**Comment by Ocupe** [comment]
> I think this aligns with the client-sdk-js defaults as well: https://github.com/livekit/client-sdk-js#audio-playback
> 
> ```
> LiveKit takes an optimistic approach so it's possible for this value to change from true to false when we encounter a browser error.
> ```

Great! Thank you for the context 👍

**Comment by lukasIO** [comment]
ah, sorry, only saw this now. What we would want is to set the init value to `room.canPlaybackAudio` instead of a hard coded value.

**Pull request merged**
