### PR TITLE
Default username displayed in input box

### PR DESCRIPTION
**Pull request by apurvbhavsar**
### Improvement

Manually added username in PreJoin Component using props not shown in Input Box. 
Fixed that issue.

### CODE REVIEW

**Comment by lukasIO** [comment]
Hi @apurvbhavsar ,
thanks for the PR! 
This makes a lot of sense in general, just thinking that we should probably go with `defaultValue` instead of `value` (https://legacy.reactjs.org/docs/uncontrolled-components.html#default-values).

**Comment by apurvbhavsar** [comment]
Yes, it will be nice and solve the issue too..

Thanks, Let me update it again

**Review by lukasIO — APPROVED** [review]
great! thank you!

**Review by Ocupe — APPROVED** [review]
Good eye for detail, thank you. 🎉

**Pull request merged**
